version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  # 빌드 전에 수행할 명령을 입력합니다.
  pre_build:
    commands:
      - echo Buile Phase >> pre_build phase...
      - npm install yarn -g
  # 빌드를 수행할 명령을 입력합니다.
  build:
    commands:
      - echo Buile Phase >> Build started on `date`
      - yarn run build
  # 빌드 후에 수행할 명령을 입력합니다.
  post_build: # 빌드 후처리
    commands:
      - echo Build started on `date`
      - rm -rf node_modules .git # 빌드 결과물 용량을 최적화 하기 위한 패키지 및 .git 삭제
      - ls -al
artifacts:  # 결과물 설정
  files:
    - '**/*'  # 모든 파일을 결과물로 생성

