
name: deploy
# 브랜치가 push 될 때 해당 액션을 실행
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
# 액션을 실행시키는 runner의 운영체제
jobs:
  build:
    runs-on: ubuntu-latest
    # ubuntu-22.04
    
    strategy:
      matrix:
        node-version: [14.x]
    # 액션의 실해 수행내용, 단계 별로 실행된다
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Create env file
        working-directory: ./server
        run: 
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}
          EOF
          
      - name: Build client files
        working-directory: ./client
        run: |
          yarn install
          yarn build
        
      - name : Zip distributions
        run: zip -r cicd-practice.zip ./client/dist ./server ./appspec.yml ./scripts

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      #s3,codeDeploy 경로와 이름 알맞게 입력
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./cicd-practice.zip s3://cicd-practice/public/

      - name: Code Deploy
        run: aws deploy create-deployment
          --application-cicd-practice-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name GroupPractice
          --s3-location bucket=cicd-practice,bundleType=zip,key=public/cicd-practice.zip
